services:
  minio:
    image: "minio/minio:latest"
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: "admin1234"
      MINIO_ROOT_PASSWORD: "admin1234"
    volumes:
      - "minio:/data/minio"
    command: minio server /data/minio --console-address ":9090"
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
  redis:
    image: "redis:latest"
    environment:
      - REDIS_PASSWORD=admin
      - REDIS_USER=admin1
      - REDIS_USER_PASSWORD=admin1
    ports:
      - "6380:6379"
    volumes:
      - "redis:/data"

  # zookeeper:
  #   image: bitnami/zookeeper:latest
  #   container_name: zookeeper
  #   restart: always
  #   ports:
  #     - "2181:2181"
  #     - "8080:8080"
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes
  #   healthcheck:
  #     test: ["CMD", "zkServer.sh", "status"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #
  # kafka:
  #   image: bitnami/kafka:latest
  #   container_name: kafka
  #   ports:
  #     - "9092:9092"
  #     - "9093:9093"
  #   environment:
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #     - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
  #     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
  #     - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
  #     - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
  #     - KAFKA_CFG_NUM_PARTITIONS=1
  #     - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=1
  #   depends_on:
  #     zookeeper:
  #       condition: service_healthy
  #   healthcheck:
  #     test: ["CMD-SHELL", "kafka-topics.sh --list --bootstrap-server localhost:9092 || exit 1"]
  #     interval: 20s
  #     timeout: 10s
  #     retries: 10

volumes:
  minio:
    driver: local
  postgres:
    driver: local
  redis:
    driver: local
